apiVersion: v1
kind: Template
metadata:
  name: petclinic-build
labels:
  app.kubernetes.io/name: petclinic
  app.kubernetes.io/instance: petclinic-master
  app.kubernetes.io/part-of: petclinic
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: petclinic
    spec:
      output:
        pushSecret:
          name: artifactory
        to:
          kind: DockerImage
          name: prj-elcavn-training-docker.artifactory.svc.elca.ch/petclinic-with-permission-plugin:luol
      source:
        type: Binary
      strategy:
        type: Docker
      resources:
        requests:
          cpu: "250m"
          memory: "2Gi"
        limits:
          cpu: "4"
          memory: "4Gi"
